### ISSUE TITLE
Exception: Invalid JTV format

### ISSUE THREAD

**Issue by Shporterator** [tataranovich/jtv2xmltv#4]
http://dkt.iptvportal.ru/jtv.zip

Traceback (most recent call last):
  File "jtv2xmltv.py", line 119, in <module>
    main()
  File "jtv2xmltv.py", line 115, in main
    convert_jtv_to_xmltv(jtv_filename, xmltv_filename, epg_timezone=tz_format)
  File "jtv2xmltv.py", line 73, in convert_jtv_to_xmltv
    channel_titles = parse_titles(titles)
  File "jtv2xmltv.py", line 19, in parse_titles
    raise Exception('Invalid JTV format')
Exception: Invalid JTV format

**Comment by tataranovich** [comment]
Provided [archive](http://dkt.iptvportal.ru/jtv.zip) is not a valid JTV data source.

According to [JTV standard description](../blob/master/docs/JTV.md) every pdt file should start with "JTV 3.x TV Program Data" string followed by three symbols with "0x0A" code. But your archive have pdt files where "JTV 3.x TV Program Data" string followed by three "0xA0" symbols instead of "0x0A".

**Comment by tataranovich** [comment]
I've added support for alternative JTV header in [v0.2.1](https://github.com/tataranovich/jtv2xmltv/releases/tag/v0.2.1).

**Comment by Shporterator** [comment]
Р’РµСЃС‘Р»С‹Рµ РёСЃС‚РѕСЂРёРё РёР
encoding epg is broken

**Comment by tataranovich** [comment]
Which python version do you use? I tested on Debian Buster using python 3.7.3 and http://dkt.iptvportal.ru/jtv.zip converted without issues.

```
wget http://dkt.iptvportal.ru/jtv.zip
jtv2xmltv -i jtv.zip -o xmltv.xml -e UTF-8
wget https://raw.githubusercontent.com/XMLTV/xmltv/master/xmltv.dtd
xmllint --noout --dtdvalid xmltv.dtd xmltv.xml
```

The same result with python 2.7.16.
